service:
  golangci-lint-version: 1.60.1
run:
  deadline: 900s
  modules-download-mode: readonly
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - exhaustruct
    - execinquery
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - importas
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  lll:
    line-length: 140
