service:
  golangci-lint-version: 1.51.x
run:
  deadline: 900s
  modules-download-mode: readonly
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - gosec
    - ifshort
    - importas
    - interfacebloat
    - interfacer
    - ireturn
    - maintidx
    - maligned
    - makezero
    - musttag
    - nestif
    - nlreturn
    - nosnakecase
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
  gofumpt:
    lang-version: "1.19"
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  lll:
    line-length: 140
